spring:
  profiles:
    active: local
jasypt:
  encryptor:
    bean: jasyptStringEncrptor
token:
  access-token-expired: 1800
  refresh-token-expired: 1209600
  client-id: ENC(N4r0cuzNvZ+3lFAgDD5V9Q==)
  client-secret: ENC(HfsRWPAZfyUscBtaJCJB7DnBS5M1C3yF)
---
spring:
  profiles: local
  resources:
    add-mappings: false
  datasource:
    watni:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      maximum-pool-size: 1
      max-lifetime: 55000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
---
spring:
  profiles: asciidoc
  resources:
    add-mappings: true