spring:
  profiles:
    active: local
jasypt:
  encryptor:
    bean: jasyptStringEncrptor
---
spring:
  profiles: local
  resources:
    add-mappings: false
---
spring:
  profiles: asciidoc
  resources:
    add-mappings: true